 // llm:content-card-migrated
 // llm:cta-migrated
 import { Button } from "@/components/ui/button";
 import { useModal } from "@/components/modal/ModalProvider";
import heroImage from "@/assets/spokane-house-cleaning.webp";
// Responsive variants (generated by scripts/optimize-images.mjs)
import hero480 from "@/assets/spokane-house-cleaning-480.webp";
import hero768 from "@/assets/spokane-house-cleaning-768.webp";
import hero1024 from "@/assets/spokane-house-cleaning-1024.webp";
// AVIF variants for <picture> source
import hero480Avif from "@/assets/spokane-house-cleaning-480.avif";
import hero768Avif from "@/assets/spokane-house-cleaning-768.avif";
import hero1024Avif from "@/assets/spokane-house-cleaning-1024.avif";
 // images now centralized via ServiceCard catalog
 import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
 import ServiceGrid from "@/components/ServiceCard/ServiceGrid";
 import ContentCard from "@/components/ContentCard/ContentCard";
 import HeroSection from "@/components/HeroSection/HeroSection";
import Icon from "@/components/ui/icon";
 import { SEO } from "@/components/seo/SEO";
 import { Helmet } from "react-helmet-async";
 import JsonLd from "@/components/seo/JsonLd";
 import { makeWebSite, makeWebPage, makeBreadcrumb, makeFAQPage } from "@/components/seo/schema";
 import { site } from "@/config/site";

export default function Home() {
  const { open } = useModal();

  // Service cards are rendered from the central catalog via ServiceGrid

  const testimonials = [
    { quote: "“Exceptional cleaning service! Reliable and thorough every time.”", name: "Emily S.", location: "Spokane Valley" },
    { quote: "“Fantastic move-out cleaning. Got my full deposit back!”", name: "David L.", location: "Liberty Lake" },
    { quote: "“Their eco-friendly products are perfect for my allergies. Highly recommend!”", name: "Rachel M.", location: "Millwood" },
  ];

  const faqs = [
    { q: "Are you insured and bonded?", a: "Yes, all our cleaners are fully insured, bonded, and background-checked." },
    { q: "What products do you use?", a: "We use safe, eco-friendly, and hypoallergenic cleaning products." },
    { q: "How do I book services?", a: "You can book via phone, email, or our online form." },
  ];

  return (
    <>
      <SEO
        title="Top Residential House Cleaning Services in Spokane, WA"
        description="Professional, eco-friendly residential house cleaning services in Spokane, Spokane Valley, Liberty Lake, and surrounding areas. Insured, bonded, and satisfaction guaranteed."
      />
      {/* Preload critical hero image to improve LCP and avoid late swaps */}
      <Helmet>
        <link rel="preload" as="image" href={hero480} media="(max-width: 480px)" fetchPriority="high" />
        <link rel="preload" as="image" href={heroImage} media="(min-width: 481px)" fetchPriority="high" />
      </Helmet>

      {/* JSON-LD: WebSite, LocalBusiness, WebPage, Breadcrumbs, FAQPage */}
      <JsonLd
        data={[
          makeWebSite(site.url),
          makeWebPage({
            siteUrl: site.url,
            path: "/",
            title: "Top Residential House Cleaning Services in Spokane, WA",
            description:
              "Professional, eco-friendly residential house cleaning services in Spokane, Spokane Valley, Liberty Lake, and surrounding areas.",
          }),
          makeBreadcrumb([
            { name: "Home", url: `${site.url}/` },
          ]),
          makeFAQPage(faqs, `${site.url}/`),
        ]}
      />

      <HeroSection
        image={heroImage}
        title={
          <h1 className="hero-title">
            Expert <span className="text-brand-gold">House Cleaning</span> in Spokane, WA
          </h1>
        }
        subtitle={
          <p className="text-lg lg:text-xl text-slate-100/95 mb-10 leading-relaxed max-w-2xl mx-auto">
            Welcome to Spokane's most trusted residential cleaning service! We provide detailed, reliable, and eco-friendly
            cleaning throughout Spokane, Spokane Valley, Liberty Lake, and nearby areas so you can enjoy more time while we
            make your home sparkle.
          </p>
        }
        actions={
          <>
            <Button
              onClick={() => open("quote")}
              aria-label="Get Free Estimate"
              variant="primary"
            >
              Get Free Estimate
            </Button>
            <a href="#services" aria-label="See Services">
              <Button
                variant="outline"
              >
                See Services
                <Icon name="ArrowRight" className="w-5 h-5 ml-2" />
              </Button>
            </a>
          </>
        }
        // HOM-001: enable aspect-ratio stabilization and provide intrinsic dimensions
        useAspect
        imageWidth={1392}
        imageHeight={752}
        // Supply responsive sources for better bandwidth on smaller screens
        // Note: Ensure scripts/optimize-images.mjs generated these files and Vite resolves imports to hashed assets at build time.
        imgSrcSet={`${hero480} 480w, ${hero768} 768w, ${hero1024} 1024w`}
        sources={[{ type: 'image/avif', srcSet: `${hero480Avif} 480w, ${hero768Avif} 768w, ${hero1024Avif} 1024w` }]}
      />

      {/* Why Choose Us */}
      <section id="why" className="py-section bg-surface scroll-mt-24" aria-labelledby="why-title">
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 animate-slide-up">
          <h2 id="why-title" className="text-3xl lg:text-4xl font-bold text-text mb-6 text-center">
            Why Choose Our House Cleaners Near You?
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-md mb-xl">
            <ContentCard className="flex items-center gap-3 min-h-[44px] py-2">
              <Icon name="ShieldCheck" className="text-teal" />
              <span className="font-medium">Insured & Bonded</span>
            </ContentCard>
            <ContentCard className="flex items-center gap-3 min-h-[44px] py-2">
              <Icon name="Leaf" className="text-teal" />
              <span className="font-medium">Eco & Pet-Safe</span>
            </ContentCard>
            <ContentCard className="flex items-center gap-3 min-h-[44px] py-2">
              <Icon name="Users" className="text-teal" />
              <span className="font-medium">Vetted Local Pros</span>
            </ContentCard>
            <ContentCard className="flex items-center gap-3 min-h-[44px] py-2">
              <Icon name="Sparkles" className="text-teal" />
              <span className="font-medium">Satisfaction Guaranteed</span>
            </ContentCard>
          </div>
          <p className="text-lg text-text max-w-3xl mx-auto text-center">
            Choosing a cleaning service is about trust and reliability. Our Spokane house cleaners are fully insured, bonded,
            and rigorously trained. We use eco-friendly, pet-safe products and back every visit with a satisfaction guarantee.
            As a local business, we prioritize personalized care and exceptional results.
          </p>
        </div>
      </section>

      {/* Services */}
      <section id="services" className="py-section bg-white scroll-mt-24" aria-labelledby="services-title">
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12">
          <div className="text-center mb-xl animate-slide-up">
            <h2 id="services-title" className="font-bold text-text mb-4">
              Comprehensive Residential Cleaning Services
            </h2>
            <p className="text-xl text-text">Professional, reliable, and tailored to your home</p>
          </div>
          <ServiceGrid ids={["residential","deep-cleaning","move-out","apartment-cleaning"]} />
        </div>
      </section>

      {/* Process */}
      <section id="process" className="py-section bg-surface scroll-mt-24" aria-labelledby="process-title">
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 animate-slide-up">
          <h2 id="process-title" className="text-3xl lg:text-4xl font-bold text-text mb-8 text-center">
            Our Simple House Cleaning Process
          </h2>
          <div className="grid md:grid-cols-4 gap-xl text-center">
            <ContentCard>
              <span className="step-number">1</span>
              <h3 className="mt-2 font-semibold">Request Your Quote</h3>
              <p className="text-sm text-text">Call or request online for a fast, customized estimate.</p>
            </ContentCard>
            <ContentCard>
              <span className="step-number">2</span>
              <h3 className="mt-2 font-semibold">Customize Your Plan</h3>
              <p className="text-sm text-text">We tailor services to your home, schedule, and preferences.</p>
            </ContentCard>
            <ContentCard>
              <span className="step-number">3</span>
              <h3 className="mt-2 font-semibold">Pro Clean Day</h3>
              <p className="text-sm text-text">Our punctual, equipped team delivers a detailed clean.</p>
            </ContentCard>
            <ContentCard>
              <span className="step-number">4</span>
              <h3 className="mt-2 font-semibold">Follow-up & Satisfaction</h3>
              <p className="text-sm text-text">We check in to ensure everything’s perfect guaranteed.</p>
            </ContentCard>
          </div>
          <p className="mt-8 text-lg text-text max-w-3xl mx-auto text-center">
            Getting your Spokane home professionally cleaned is straightforward with our seamless process. Request a free quote,
            choose your plan and schedule, and enjoy a refreshed home every time.
          </p>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-section bg-white scroll-mt-24" aria-labelledby="pricing-title">
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 text-center animate-slide-up">
          <h2 id="pricing-title" className="text-3xl lg:text-4xl font-bold text-text mb-4">Transparent Pricing & Free Estimates</h2>
          <p className="text-lg text-text max-w-3xl mx-auto mb-6">
            Costs vary by home size, cleaning type, and frequency. Standard services typically start around $110 per visit.
            Deep or move-out cleanings are quoted individually. Recurring plans offer meaningful savings.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center items-center">
            <Button
              onClick={() => open("quote")}
              variant="primary"
            >
              Get My Free Estimate
            </Button>
          </div>
        </div>
      </section>

      {/* Service Areas */}
      <section id="areas" className="py-section bg-gradient-to-b from-surface via-surface/95 to-white scroll-mt-24" aria-labelledby="areas-title">
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 animate-slide-up">
          <h2 id="areas-title" className="text-3xl lg:text-4xl font-bold text-text mb-4 text-center">Our Spokane Area Service Locations</h2>
          <p className="text-lg text-text max-w-3xl mx-auto text-center mb-8">
            Spokane, Spokane Valley, Liberty Lake, and Greenacres.
          </p>

          {/* Exactly four location cards linking to the four location pages */}
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-xl mt-8">
            <ContentCard as="a" href="/locations/spokane" interactive className="group text-center transition-all duration-300 hover:scale-[1.01] hover:shadow-lg bg-gray-50/80 border border-gray-200/60 rounded-xl p-6 hover:bg-white">
              <h3 className="text-base font-bold mb-2 text-gray-900">Spokane</h3>
              <p className="text-xs text-gray-600 max-w-[120px] mx-auto leading-relaxed">Citywide coverage</p>
            </ContentCard>
            <ContentCard as="a" href="/locations/spokane-valley" interactive className="group text-center transition-all duration-300 hover:scale-[1.01] hover:shadow-lg bg-gray-50/80 border border-gray-200/60 rounded-xl p-6 hover:bg-white">
              <h3 className="text-base font-bold mb-2 text-gray-900">Spokane Valley</h3>
              <p className="text-xs text-gray-600 max-w-[120px] mx-auto leading-relaxed">From Opportunity to Veradale</p>
            </ContentCard>
            <ContentCard as="a" href="/locations/liberty-lake" interactive className="group text-center transition-all duration-300 hover:scale-[1.01] hover:shadow-lg bg-gray-50/80 border border-gray-200/60 rounded-xl p-6 hover:bg-white">
              <h3 className="text-base font-bold mb-2 text-gray-900">Liberty Lake</h3>
              <p className="text-xs text-gray-600 max-w-[120px] mx-auto leading-relaxed">Lakefront to town center</p>
            </ContentCard>
            <ContentCard as="a" href="/locations/greenacres" interactive className="group text-center transition-all duration-300 hover:scale-[1.01] hover:shadow-lg bg-gray-50/80 border border-gray-200/60 rounded-xl p-6 hover:bg-white">
              <h3 className="text-base font-bold mb-2 text-gray-900">Greenacres</h3>
              <p className="text-xs text-gray-600 max-w-[120px] mx-auto leading-relaxed">River-adjacent & neighborhoods</p>
            </ContentCard>
          </div>

          <div className="mt-8 text-center">
            <a href="/locations" className="inline-flex w-full sm:w-auto sm:justify-center">
              <Button
                variant="secondary"
                className="w-full sm:w-72 mx-auto rounded-lg hover:bg-gray-100 transition-colors duration-200"
              >
                View full service area
              </Button>
            </a>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="py-section bg-white scroll-mt-24" aria-labelledby="testimonials-title">
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 animate-slide-up">
          <h2 id="testimonials-title" className="text-3xl lg:text-4xl font-bold text-text mb-8 text-center">
            Real Customer Reviews & Testimonials
          </h2>
          <div className="grid md:grid-cols-3 gap-xl">
            {testimonials.map((t, i) => (
              <ContentCard key={i}>
                <p className="italic text-text">{t.quote}</p>
                <p className="mt-4 font-semibold">{t.name}</p>
                <p className="text-sm text-gray-500">{t.location}</p>
              </ContentCard>
            ))}
          </div>
        </div>
      </section>

      {/* FAQs */}
      <section id="faqs" className="py-section bg-surface scroll-mt-24" aria-labelledby="faqs-title">
        <div className="max-w-3xl mx-auto px-6 sm:px-10 lg:px-12 animate-slide-up">
          <div className="text-center mb-12">
            <h2 id="faqs-title" className="text-3xl lg:text-4xl font-bold text-text mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-lg text-text max-w-2xl mx-auto">
              Get answers to common questions about our cleaning services
            </p>
          </div>
          <div className="rounded-2xl bg-gradient-to-b from-white/95 to-white/90 backdrop-blur-sm shadow-lg border border-white/20 p-2">
            {/* HOM-002: FAQ accordion
               - Uses Radix Accordion primitives which render a semantic <button> trigger with correct ARIA:
                 aria-expanded toggles and aria-controls points to content id (managed by Radix).
               - Root cause of regression: trigger lacked explicit type="button" in our UI primitive. In certain contexts,
                 this could cause no-op clicks or unintended form submits blocking toggle behavior.
                 Fix applied in UI primitives: see AccordionTrigger in client/src/components/ui/accordion.tsx.
               - Keyboard: Space/Enter toggle works; focus ring is visible via focus-visible utilities. */}
            <Accordion type="single" collapsible className="w-full rounded-xl bg-white/50 shadow-sm divide-y divide-gray-100">
            {faqs.map((f, i) => (
              <AccordionItem key={i} value={`item-${i + 1}`}>
                <AccordionTrigger className="text-left py-4 px-4"><h3>Do house cleaners in Spokane bring their own supplies?</h3></AccordionTrigger>
                <AccordionContent className="px-4 pb-4">{f.a}</AccordionContent>
              </AccordionItem>
            ))}

            <AccordionItem value="item-deep-clean-included">
              <AccordionTrigger className="text-left py-4 px-4"><h3>What’s included in a deep house cleaning in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                A deep house cleaning in Spokane usually includes scrubbing bathrooms and kitchens, cleaning baseboards, dusting vents and ceiling fans, and sanitizing high-touch areas. It goes beyond standard cleaning to cover hard-to-reach spots.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-maid-cost">
              <AccordionTrigger className="text-left py-4 px-4"><h3>How much does maid service cost in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Maid service in Spokane typically costs between $100 and $500+ per visit, depending on the size of your home and how detailed the cleaning is. Deep cleaning or move-out services will cost more.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-moveout-required">
              <AccordionTrigger className="text-left py-4 px-4"><h3>Is move-out cleaning required when I leave a rental in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Yes, many Spokane landlords require professional move-out cleaning as part of the lease. Hiring a local cleaning service ensures you meet the standards for getting your deposit back.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-eco-friendly">
              <AccordionTrigger className="text-left py-4 px-4"><h3>Are there eco-friendly house cleaners in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Yes, several Spokane cleaning companies offer green cleaning options using non-toxic, eco-friendly products that are safe for kids and pets. Cleaners Ready 2 GO is Spokane’s favorite.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-how-often">
              <AccordionTrigger className="text-left py-4 px-4"><h3>How often should I get a professional house cleaning in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Most Spokane residents schedule cleanings every two weeks or once a month. Homes with pets, kids, or allergy concerns may benefit from weekly cleanings.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-supplies">
              <AccordionTrigger className="text-left py-4 px-4">Do house cleaners in Spokane bring their own supplies?</AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Yes, most Spokane cleaning companies bring their own equipment and eco-friendly products. You can request specific products or methods if needed.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-same-day">
              <AccordionTrigger className="text-left py-4 px-4"><h3>Can I get same-day house cleaning in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Some companies offer same-day or next-day house cleaning in Spokane, but availability depends on the schedule. Booking ahead is recommended for deep cleans or larger jobs.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-deep-before-selling">
              <AccordionTrigger className="text-left py-4 px-4"><h3>Is deep cleaning worth it before listing my Spokane home for sale?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Definitely. Deep cleaning your Spokane home before listing can boost curb appeal, make a better impression on buyers, and help your home sell faster.
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-find-best">
              <AccordionTrigger className="text-left py-4 px-4"><h3>How do I find the best house cleaning service near me in Spokane?</h3></AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                Look for Spokane cleaning companies with great reviews, bonded and insured teams, and satisfaction guarantees. Ask about their cleaning checklists and eco-friendly options.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
          </div>
        </div>
      </section>

      {/* Final CTA / Closing */}
      <section id="cta" className="py-section bg-white relative overflow-hidden scroll-mt-24" aria-labelledby="cta-title">
        <div className="relative max-w-4xl mx-auto text-center px-6 sm:px-10 lg:px-12 animate-slide-up">
          <h2 id="cta-title" className="text-4xl lg:text-6xl font-bold text-text mb-6 leading-tight">
            Book Your Cleaning Service Today!
          </h2>
          <p className="text-lg lg:text-xl text-text mb-10">
            We promise reliable, thorough, and eco-friendly cleaning that exceeds expectations. Get your free estimate or book now.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center items-center">
            <Button
              onClick={() => open("quote")}
              aria-label="Get Free Estimate"
              variant="primary"
            >
              Get Free Estimate
            </Button>
            <Button
              onClick={() => open("booking")}
              aria-label="Schedule Cleaning"
              variant="primary"
            >
              Schedule Cleaning
            </Button>
          </div>
          {/* Removed call and email buttons as requested */}
        </div>
      </section>

    </>
  );
}
