// llm:brand-config-migrated
export const brand = {
  phone: "(509) 210-6800",
  email: "info@cleanersready2go.com",
  address: {
    street: "123 E Sprague Ave",
    city: "Spokane",
    state: "WA",
    zip: "99202",
  },
  hours: "7 days a week, 5:00am to 7:00pm",
  serviceAreas: {
    cities: [
      "Spokane",
      "Spokane Valley",
      "Liberty Lake",
      "Cheney",
      "Otis Orchards",
      "Airway Heights",
      "Mead",
      "Colbert",
      "Greenacres",
      "Veradale",
      "Millwood",
      "Dishman",
      "Trentwood",
      "Ponderosa",
      "Barker & Sprague Corridor",
    ],
    zips: ["99016", "99037", "99206", "99212", "99216", "99217", "99201", "99208"],
  },
  logo: "/assets/icon_logo-256.webp",
  sameAs: [
    "https://www.yelp.com/biz/cleaners-ready-2go-spokane-valley?osq=Cleaners+Ready+2GO",
    "https://pro.porch.com/spokane-valley-wa/home-cleaners/cleaners-ready-2go/pp",
    "https://homeguide.com/wa/spokane-valley/house-cleaning/cleaners-ready-2go-Sz1J2BzgI",
    "https://www.facebook.com/profile.php?id=61579665782441",
    "https://ccfs.sos.wa.gov/#/BusinessSearch/BusinessInformation",
  ],
};
